version: "3"

services:
  app:
    container_name: docker-node-mongo
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      -  .:/usr/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'